#!/bin/bash

hg_sh_path=$1
source ~/.bashrc                              
source $hg_sh_path/hg-colors
source $hg_sh_path/hg-sh-aliases
source $hg_sh_path/hg-completion.bash
source $hg_sh_path/hg-scm-prompt




