#!/bin/bash

#set -x                              

set_hg_sh_path() {
  script_path=`$readlink_cmd  $0`
  export HG_SH_PATH=`dirname $script_path`
  export HG_SH_PATH=$(cd "$HG_SH_PATH" && pwd)  
}

hg_bootstrap() {
  hg_sh_path=$1
  source ~/.bashrc                              
  source $hg_sh_path/hg-colors
  source $hg_sh_path/hg-sh-aliases
  source $hg_sh_path/hg-completion.bash
  source $hg_sh_path/hg-scm-prompt
}

################################ * main *

readlink_cmd='readlink -f'

if uname -a | grep -qi "darwin" ; then
  readlink_cmd='readlink.sh'
fi

path=$HG_SH_PATH
set_hg_sh_path

if [ "$0" != 'bash' ]; then
  exec /usr/bin/env bash --rcfile "$0" "$@"
else  
  hg_bootstrap $path
fi


