#!/bin/bash
                              
set -e
#set -x                              

readlink_cmd='readlink -f'

if uname -a | grep -qi "darwin" ; then
  readlink_cmd='readlink.sh'
fi

path=$HG_SH_PATH
#unset in case we crash
#if [[ "$HG_SH_PATH" == "" ]]; then
  script_path=`$readlink_cmd  $0`
  export HG_SH_PATH=`dirname $script_path`
  export HG_SH_PATH=$(cd "$HG_SH_PATH" && pwd)
#fi                                            


if [ "$0" != 'bash' ]; then
  exec /usr/bin/env bash --rcfile "$0" "$@"
else  
  source $path/hg-bootstrap $path
fi

